[api]

domain = ""
publicDomain = ""
port = 4560
adminPassword = ""

[network]

heartbeatInterval = 3000
latestVersion = ""
publicDir = "web/dist"
webchatIndex = "index.html"
uploadDir = "files/uploads"
uploadPublicBase = "/app/uploads"

[rtc]

relayOnly = true
turnUrls = []
turnUsername = ""
turnCredential = ""

[database]

kind = "sqlite"
url = "sqlite://files/qxp.sqlite"

[security]

adminIds = ["7289483668878565"]
registerEnabled = true
